=== AirwaveDB/database/schema/station.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/AirwaveDB/database/blob/main/schema/station.schema.json",
  "title": "AirwaveDB Station",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "country",
    "subdivision",
    "languages",
    "categories",
    "tags",
    "homepage",
    "favicon",
    "type",
    "sourceCount",
    "updatedAt"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^awb_[0-9a-f]{20}$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
    },
    "subdivision": {
      "type": ["string", "null"]
    },
    "languages": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[a-z]{2,3}$"
      }
    },
    "categories": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9][a-z0-9-]*$"
      }
    },
    "tags": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "homepage": {
      "type": ["string", "null"]
    },
    "favicon": {
      "type": ["string", "null"]
    },
    "type": {
      "enum": ["public", "community", "college", "internet", null]
    },
    "sourceCount": {
      "type": "integer",
      "minimum": 1
    },
    "updatedAt": {
      "type": ["string", "null"]
    }
  }
}

=== AirwaveDB/database/data/stations/PF.json
[
  {
    "id": "awb_49dbca638a727a7d9422",
    "name": "Abdulbasit Abdulsamad",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_2228c8052431e49cbb2b",
    "name": "HITI FM",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr",
      "ty"
    ],
    "categories": [],
    "tags": [],
    "homepage": "http://hitifm.fr/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T07:08:10Z"
  },
  {
    "id": "awb_f5519376cdda88334356",
    "name": "Hiti FM",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "en",
      "fr"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "pop music",
      "pop-music"
    ],
    "homepage": "https://hiti-fm.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_1d7937d18b1a22988cd1",
    "name": "Nostalgie 100% Francais 80",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr"
    ],
    "categories": [
      "oldies",
      "pop"
    ],
    "tags": [
      "80's",
      "80s",
      "french radio",
      "pop"
    ],
    "homepage": "https://www.nostalgie.fr/webradios/mur-des-radios/nostalgie-100-francais-80",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_374dfd4ff643fd8e00a4",
    "name": "Polynésie 1ère",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr"
    ],
    "categories": [
      "news",
      "pop"
    ],
    "tags": [
      "information",
      "local music",
      "local news",
      "pop"
    ],
    "homepage": "https://la1ere.francetvinfo.fr/polynesie/",
    "favicon": "https://la1ere.francetvinfo.fr/favicon.ico",
    "type": null,
    "sourceCount": 3,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_b7d9d78e6a384bb3d69c",
    "name": "Polynesie Première",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://la1ere.francetvinfo.fr/polynesie/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Polyn%C3%A9sie_La_1%C3%A8re_-_Logo_2018.svg/langfr-200px-Polyn%C3%A9sie_La_1%C3%A8re_-_Logo_2018.svg.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T05:29:20Z"
  },
  {
    "id": "awb_68431686305f1bdd4b15",
    "name": "Radio 1 PF",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://www.radio1.pf/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_24986ca135f35d59cbef",
    "name": "Radio 1 Tahiti",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "local information",
      "local music",
      "pop music"
    ],
    "homepage": "https://www.radio1.pf/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T00:53:11Z"
  },
  {
    "id": "awb_40399169756d1ba8f164",
    "name": "Radio Melod'iles",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr",
      "ty"
    ],
    "categories": [],
    "tags": [
      "local",
      "tahitian"
    ],
    "homepage": "https://radiomelodiles.radiostream321.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-08-04T20:50:47Z"
  },
  {
    "id": "awb_fc8e8c99cb47183918bd",
    "name": "Radio1 Tahiti",
    "country": "PF",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.radio1.pf/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:04Z"
  },
  {
    "id": "awb_7df80402e695d83ab937",
    "name": "Tiare FM",
    "country": "PF",
    "subdivision": null,
    "languages": [
      "fr"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "local information",
      "local music",
      "pop music",
      "pop-music"
    ],
    "homepage": "https://www.tiarefm.pf/",
    "favicon": "https://www.tiarefm.pf/favicon.ico",
    "type": null,
    "sourceCount": 3,
    "updatedAt": "2026-08-23"
  }
]

=== AirwaveDB/database/data/stations/MR.json
[
  {
    "id": "awb_93ab026757dff54aefe1",
    "name": "Abdulbasit Abdulsamad",
    "country": "MR",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T07:22:38Z"
  }
]

=== AirwaveDB/database/data/stations/BH.json
[
  {
    "id": "awb_21b4f5cc4d8e3d895c2c",
    "name": ".. مختصر التفسير",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-01-14T22:54:44Z"
  },
  {
    "id": "awb_206d1be59da77e899d4a",
    "name": ".beautiful recitation",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_2898cc19747eb74c44eb",
    "name": ".Quran",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:04Z"
  },
  {
    "id": "awb_d8d08793d30ff46dd7f8",
    "name": ".إذاعة ماهر المعيقلي",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:04Z"
  },
  {
    "id": "awb_1961041e862e442c3c8e",
    "name": ".القارئ محمد أيوب",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:44Z"
  },
  {
    "id": "awb_1ac1996b8731fa705509",
    "name": ".القرآن",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_c04872056b71c49734a2",
    "name": "Abdulbasit Abdulsamad",
    "country": "BH",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_a50853a5eba0bdb69298",
    "name": "AFN 360 Bahrain",
    "country": "BH",
    "subdivision": null,
    "languages": [
      "en"
    ],
    "categories": [],
    "tags": [
      "american forces network"
    ],
    "homepage": "http://www.afneurope.net/AFN-360/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T06:35:42Z"
  },
  {
    "id": "awb_7b2c39226272f5e23980",
    "name": "AFN GO BAHRAIN",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://afngo.net/afneurope/Aviano/radio/Bahrain",
    "favicon": "https://afngo.net/static/media/Bahrain.24eaa086d110f57b7e38.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_2faf19a518a66c52304b",
    "name": "Bahrain 106.1 FM",
    "country": "BH",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [
      "religious"
    ],
    "tags": [
      "bahrain",
      "islam",
      "quran"
    ],
    "homepage": "https://www.mia.gov.bh/media-center/quran-kareem-106-1",
    "favicon": "https://www.mia.gov.bh/wp-content/uploads/2023/02/cropped-Royal-Emblem-192x192.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-04-30T17:21:02Z"
  },
  {
    "id": "awb_549a67fe8f5767a3dee6",
    "name": "Bahrain FM 93.3",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [
      "bahrain",
      "bahrain fm 93.3"
    ],
    "homepage": "https://www.mia.gov.bh/media-center/bahrain-fm-93-3/?lang=en",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:10Z"
  },
  {
    "id": "awb_794633a2f303ec1f1cc6",
    "name": "Bahrain Quran 106.1 FM",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "religious"
    ],
    "tags": [
      "bahrain",
      "quran"
    ],
    "homepage": "https://www.mia.gov.bh/media-center/quran-kareem-106-1/?lang=en",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-04-30T09:15:56Z"
  },
  {
    "id": "awb_8a3e7ed5dbeb62f7455a",
    "name": "ccc",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://m-aac.cbs.co.kr/mweb_cbs939/_definst_/cbs939.stream/playlist.m3u8",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:10Z"
  },
  {
    "id": "awb_b065d36804b9c05ecb56",
    "name": "Live FM",
    "country": "BH",
    "subdivision": null,
    "languages": [
      "en",
      "hi",
      "kn",
      "ml",
      "ta",
      "te",
      "ur"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://www.livefm.bh/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-01-15T04:26:23Z"
  },
  {
    "id": "awb_4234f9f8cb4aee27f783",
    "name": "Monte Carlo Doualiya",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.mc-doualiya.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_8f68692463ed18fd7ca6",
    "name": "Panorama FM",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.mbc.net/channels",
    "favicon": "https://www.mbc.net/apple-touch-icon.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:07Z"
  },
  {
    "id": "awb_8feaf12f79608dd9d3a2",
    "name": "Traditional Radio 95.0",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [
      "bahrain",
      "traditional radio 95.0"
    ],
    "homepage": "https://www.mia.gov.bh/media-center/traditional-radio-95-0/?lang=en",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:09Z"
  },
  {
    "id": "awb_0a04a2178e64923ef29e",
    "name": "Voice of Ummah",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.voiceofummah.org/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:12Z"
  },
  {
    "id": "awb_7efec32d8e0c82e8f847",
    "name": "إذاعة القرآن الكريم",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": "https://i.pinimg.com/564x/3a/a1/a1/3aa1a107c9434ca52b42b2dd0ffc896f.jpg",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_8cd3b8455bc61b378b24",
    "name": "اذاعة القرآن الكريم",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:03Z"
  },
  {
    "id": "awb_4ec183d388ead5967497",
    "name": "تفسير بن عثيمين رحمه الله",
    "country": "BH",
    "subdivision": null,
    "languages": [],
    "categories": [
      "classical"
    ],
    "tags": [
      "classical"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  }
]

=== AirwaveDB/database/data/stations/GU.json
[
  {
    "id": "awb_9c2f15d63ff93ddca141",
    "name": "104.3 Boss FM",
    "country": "GU",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://boss104.gu/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_7b608b0dcdea674d77b4",
    "name": "Abdulbasit Abdulsamad",
    "country": "GU",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_dd7788b462b609538b41",
    "name": "Harvest Family Radio Guam",
    "country": "GU",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://khmg.org/",
    "favicon": "https://khmg.org/wp-content/uploads/logo_330.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_d82365e81ce82a1246d5",
    "name": "KIJI 104.3 FM Hagatna, Guam",
    "country": "GU",
    "subdivision": "Hagatna",
    "languages": [
      "en"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "classic hits"
    ],
    "homepage": "https://boss104.gu/",
    "favicon": "https://kiji-fm.linkedupradio.com/assets/images/logo/logo.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-12T11:09:53Z"
  },
  {
    "id": "awb_9a88d28b15b6106ce849",
    "name": "KUSG",
    "country": "GU",
    "subdivision": null,
    "languages": [
      "en"
    ],
    "categories": [
      "news",
      "talk"
    ],
    "tags": [
      "news",
      "talk"
    ],
    "homepage": "http://thepoint.gu/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_7e51013fc18632297cda",
    "name": "TFC Guam",
    "country": "GU",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [
      "filipino"
    ],
    "homepage": "https://mytfc.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:09Z"
  }
]

=== AirwaveDB/database/data/stations/AM.json
[
  {
    "id": "awb_3b3fb44497bff5f7aac0",
    "name": "Abdulbasit Abdulsamad",
    "country": "AM",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_27286ed2ae761b87a5ab",
    "name": "Armenian Bible Study Radio",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://armenianbiblestudy.com/",
    "favicon": "https://armenianbiblestudy.com/wp-content/uploads/2021/07/ABS-Logo.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_c82795d54c31af639c0f",
    "name": "Armenian Christian Radio - Bashde Radio",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "http://bashde.org/",
    "favicon": "http://bashde.org/favicon.ico",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_08a84e7502607c0b2990",
    "name": "Armenian Radio",
    "country": "AM",
    "subdivision": "Yerevan",
    "languages": [
      "en",
      "hy",
      "ru"
    ],
    "categories": [],
    "tags": [
      "entertainment",
      "pop music",
      "pop-music"
    ],
    "homepage": "https://www.laarmenianradio.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_d54c8dcaf7082c8ed44b",
    "name": "Fama",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.radiofama.am/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:03Z"
  },
  {
    "id": "awb_8132ef44b24c57cf5d82",
    "name": "Jazz FM 106.9 Yerevan Radio",
    "country": "AM",
    "subdivision": null,
    "languages": [
      "hy"
    ],
    "categories": [
      "jazz"
    ],
    "tags": [
      "jazz"
    ],
    "homepage": "https://www.radiojazzfm.am/",
    "favicon": "https://www.radiojazzfm.am/img/core-img/logo2.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-05-25T22:08:43Z"
  },
  {
    "id": "awb_79e6576419febe056260",
    "name": "Kiss FM Armenia",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.kissfm.am/en/home",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:07Z"
  },
  {
    "id": "awb_17d3e006c35f77e6c5ec",
    "name": "Lav Radio",
    "country": "AM",
    "subdivision": null,
    "languages": [
      "hy"
    ],
    "categories": [],
    "tags": [
      "armenian"
    ],
    "homepage": "https://www.lavradio.am/",
    "favicon": "https://www.lavradio.am/wp-content/uploads/2020/08/lav350.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_796ac025153adc527a86",
    "name": "Lav Radio Mix",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://lavradio.am/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:10Z"
  },
  {
    "id": "awb_b880dc8e8bbb094913c0",
    "name": "LOVE RADIO",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [
      "international"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_194c9e2ccc30badae358",
    "name": "Lratvakan Radio",
    "country": "AM",
    "subdivision": null,
    "languages": [
      "hy"
    ],
    "categories": [
      "news"
    ],
    "tags": [
      "armenian",
      "debates & interviews",
      "news"
    ],
    "homepage": "https://www.lratvakan.am/",
    "favicon": "https://www.lratvakan.am/media/company/logo/corporate-logo_IAoQCpL.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-05-25T22:17:29Z"
  },
  {
    "id": "awb_5847e45e21c31a001eae",
    "name": "MFM Music Radio",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [
      "pop"
    ],
    "tags": [
      "modern",
      "music",
      "pop"
    ],
    "homepage": "https://www.mfm.am/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_2ed3489ab724510ab496",
    "name": "Radio Marshall",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.radiomarshall.am/",
    "favicon": "https://www.radiomarshall.am/images/logo.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_524e12f6ab81ff732238",
    "name": "XFM Radio",
    "country": "AM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.xfm.am/",
    "favicon": "http://www.lavradio.am/wp-content/uploads/2019/05/xfmlg.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  }
]

=== AirwaveDB/database/data/stations/GQ.json
[
  {
    "id": "awb_fddfd4c174f356b69144",
    "name": "Abdulbasit Abdulsamad",
    "country": "GQ",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T08:25:40Z"
  },
  {
    "id": "awb_409e17585af6321eb68f",
    "name": "Exa FM",
    "country": "GQ",
    "subdivision": null,
    "languages": [
      "es"
    ],
    "categories": [
      "news",
      "pop",
      "rock"
    ],
    "tags": [
      "93.3 fm",
      "entretenimiento",
      "español",
      "estación",
      "exa",
      "exa fm",
      "fm",
      "juvenil",
      "la estación exacta",
      "la estación naranja",
      "moi merino",
      "mvs",
      "mvs noticias",
      "mvs radio",
      "música en español e inglés",
      "música pop",
      "ponte exa",
      "pop",
      "pop en español e inglés",
      "pop music",
      "pop rock",
      "radio"
    ],
    "homepage": "https://www.exafm.com/veracruz/",
    "favicon": "https://i.iheart.com/v3/re/new_assets/5f9883c7cde5eff19e6eabac",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T00:26:31Z"
  }
]

=== AirwaveDB/database/data/stations/MM.json
[
  {
    "id": "awb_81a06d57cd68fe490b4a",
    "name": "Abdulbasit Abdulsamad",
    "country": "MM",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T08:24:53Z"
  },
  {
    "id": "awb_ad8232b8991d7b60f758",
    "name": "Cherry FM",
    "country": "MM",
    "subdivision": "Shan",
    "languages": [
      "my"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "music pop",
      "music variety",
      "variety"
    ],
    "homepage": "http://www.cherryfmmym.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 3,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_11c698b688ea4214d643",
    "name": "DWG Radio Bumese",
    "country": "MM",
    "subdivision": null,
    "languages": [
      "my"
    ],
    "categories": [
      "religious"
    ],
    "tags": [
      "christian",
      "gospel"
    ],
    "homepage": "https://www.streamplus.de/",
    "favicon": "https://www.streamplus.de/img/favico.ico",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T06:20:33Z"
  },
  {
    "id": "awb_54150b805c60d9ebf2c0",
    "name": "MandalayFM",
    "country": "MM",
    "subdivision": null,
    "languages": [
      "my"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://raddio.net/",
    "favicon": "https://cdn.raddio.net/img/icons/apple-icon-120x120.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_b98200893031b919f4bd",
    "name": "Padamyar FM",
    "country": "MM",
    "subdivision": null,
    "languages": [
      "my"
    ],
    "categories": [],
    "tags": [],
    "homepage": "http://padamyarfm.com/",
    "favicon": "https://padamyarfm.com.mm/favicon-32x32.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-05-17T08:03:35Z"
  }
]

=== AirwaveDB/database/data/stations/KI.json
[
  {
    "id": "awb_27e376e2fe31bd49784b",
    "name": "Radio Kiribati 1440 kHz",
    "country": "KI",
    "subdivision": null,
    "languages": [],
    "categories": [
      "news"
    ],
    "tags": [
      "music",
      "news"
    ],
    "homepage": "https://en.wikipedia.org/wiki/Radio_Kiribati",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-03-08T18:37:51Z"
  }
]
