=== AirwaveDB/database/schema/station.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/AirwaveDB/database/blob/main/schema/station.schema.json",
  "title": "AirwaveDB Station",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "country",
    "subdivision",
    "languages",
    "categories",
    "tags",
    "homepage",
    "favicon",
    "type",
    "sourceCount",
    "updatedAt"
  ],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^awb_[0-9a-f]{20}$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "country": {
      "type": "string",
      "pattern": "^[A-Z]{2}$"
    },
    "subdivision": {
      "type": ["string", "null"]
    },
    "languages": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[a-z]{2,3}$"
      }
    },
    "categories": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[a-z0-9][a-z0-9-]*$"
      }
    },
    "tags": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "homepage": {
      "type": ["string", "null"]
    },
    "favicon": {
      "type": ["string", "null"]
    },
    "type": {
      "enum": ["public", "community", "college", "internet", null]
    },
    "sourceCount": {
      "type": "integer",
      "minimum": 1
    },
    "updatedAt": {
      "type": ["string", "null"]
    }
  }
}

=== AirwaveDB/database/data/stations/PM.json
[
  {
    "id": "awb_78c4f05dba2bca8e555b",
    "name": "Abdulbasit Abdulsamad",
    "country": "PM",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": "https://mp3islam.com/favicon.ico",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T04:44:38Z"
  },
  {
    "id": "awb_f06caed5f666bad66a32",
    "name": "Archipel FM SPM (975) 103.3",
    "country": "PM",
    "subdivision": "France",
    "languages": [
      "fr"
    ],
    "categories": [
      "public"
    ],
    "tags": [
      "public radio"
    ],
    "homepage": "https://www.facebook.com/Radio-Archipel-FM-1033-985-173650349352754/",
    "favicon": "https://www.facebook.com/favicon.ico",
    "type": "public",
    "sourceCount": 1,
    "updatedAt": "2026-01-15T06:09:01Z"
  },
  {
    "id": "awb_061943e6eb7cc7ba4c2a",
    "name": "La 1ere Saint Pierre et Miquelon (975)",
    "country": "PM",
    "subdivision": "France",
    "languages": [],
    "categories": [
      "public"
    ],
    "tags": [
      "public radio"
    ],
    "homepage": "https://la1ere.francetvinfo.fr/saintpierremiquelon/",
    "favicon": "https://www.google.com/url?sa=i&url=http%3A%2F%2Ffr-fr.radioline.co%2Fecouter-rfo-radio-saint-pierre-et-miquelon&psig=AOvVaw1XKDAabRkc01Z7sN8DoKjk&ust=1637792164850000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCKCbmrTBr_QCFQAAAAAdAAAAABAE",
    "type": "public",
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:03Z"
  }
]

=== AirwaveDB/database/data/stations/SO.json
[
  {
    "id": "awb_222c03353c45e5c0ab99",
    "name": "Idaacadda Subaxnimo VOA",
    "country": "SO",
    "subdivision": null,
    "languages": [],
    "categories": [
      "news"
    ],
    "tags": [
      "news"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:03Z"
  },
  {
    "id": "awb_bd1e8a9122a141ae71fd",
    "name": "Radio Baidoa 89.5 FM",
    "country": "SO",
    "subdivision": "Ba",
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://zeno.fm/radio/raadiyo-baydhabo/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-08-30T15:34:03Z"
  }
]

=== AirwaveDB/database/data/stations/SL.json
[
  {
    "id": "awb_cb4c84109ba99da81341",
    "name": "Choice FM 93.3",
    "country": "SL",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.choicefmsl.com/",
    "favicon": "https://static.wixstatic.com/media/247284_502bcb35bb7d4262880f9ea7fa748868~mv2.jpg/v1/fill/w_180%2Ch_180%2Clg_1%2Cusm_0.66_1.00_0.01/247284_502bcb35bb7d4262880f9ea7fa748868~mv2.jpg",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:04Z"
  },
  {
    "id": "awb_a97142e24685bfea4bad",
    "name": "Sierra Network Radio",
    "country": "SL",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [
      "african music"
    ],
    "homepage": "https://snradio.net/snradio/",
    "favicon": "https://cdn.onlineradiobox.com/img/l/0/47840.v6.png",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-01-14T22:54:04Z"
  }
]

=== AirwaveDB/database/data/stations/ER.json
[
  {
    "id": "awb_adf7efa89124c6344697",
    "name": "Abdulbasit Abdulsamad",
    "country": "ER",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_afce12a1858ec4bc9550",
    "name": "Eri-TV",
    "country": "ER",
    "subdivision": null,
    "languages": [
      "ti"
    ],
    "categories": [
      "news"
    ],
    "tags": [
      "drama",
      "news"
    ],
    "homepage": "https://jmc-live.ercdn.net/eritreatv/eritreatv.m3u8",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-04-10T00:35:03Z"
  },
  {
    "id": "awb_4a7c436871074b9666b6",
    "name": "Eritrean Music",
    "country": "ER",
    "subdivision": null,
    "languages": [
      "am"
    ],
    "categories": [],
    "tags": [
      "amharic",
      "tigrigna"
    ],
    "homepage": "https://linuxfreelancer.com/shoutcast-internet-radio",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/800px-Flag_of_Eritrea.svg.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T07:58:24Z"
  },
  {
    "id": "awb_78cc5ae40e34bb7ff8a7",
    "name": "Eritrean/Ethiopian music",
    "country": "ER",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://linuxfreelancer.com/shoutcast-internet-radio",
    "favicon": "https://en.wikipedia.org/wiki/File:Flag_of_Eritrea.svg",
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_387ef0c6825589fe4685",
    "name": "hip hop",
    "country": "ER",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [
      "music"
    ],
    "homepage": "https://yonaskassahun011.wixsite.com/selamcoffee-1",
    "favicon": "https://www.wix.com/favicon.ico",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:04Z"
  }
]

=== AirwaveDB/database/data/stations/VG.json
[
  {
    "id": "awb_b2ec0bb7cdec123ffac1",
    "name": "Abdulbasit Abdulsamad",
    "country": "VG",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T23:39:08Z"
  },
  {
    "id": "awb_b2b0e5d78ae28cd200f3",
    "name": "Burning Rockers",
    "country": "VG",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "http://www.burningrockers.com/",
    "favicon": "http://www.burningrockers.com/images/LOGO_TOP.jpg",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-02-02T15:44:04Z"
  },
  {
    "id": "awb_3126a154520f50480177",
    "name": "Soggy Dollar Radio",
    "country": "VG",
    "subdivision": "Jost",
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.soggydollar.com/",
    "favicon": "https://www.soggydollar.com/favicon.ico",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-03-09T08:01:13Z"
  }
]

=== AirwaveDB/database/data/stations/MZ.json
[
  {
    "id": "awb_9cde7e29537508a990fe",
    "name": "Abdulbasit Abdulsamad",
    "country": "MZ",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_fdb0d333fd69d34dd873",
    "name": "Grandes Clássicos da Música Moçambicana",
    "country": "MZ",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [
      "international",
      "r&b/urban"
    ],
    "homepage": "https://zeno.fm/radio/grandes-classicos-da-musica-mocambicana/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-01-14T22:54:09Z"
  },
  {
    "id": "awb_f217e8586502fcdac1cf",
    "name": "LM Radio",
    "country": "MZ",
    "subdivision": null,
    "languages": [
      "en",
      "pt"
    ],
    "categories": [],
    "tags": [
      "easy listening",
      "easy-listening"
    ],
    "homepage": "https://lmradio.co.mz/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_51fb0ab00fb2a659a9f8",
    "name": "LM Radio Mozambique",
    "country": "MZ",
    "subdivision": null,
    "languages": [
      "en",
      "pt"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://lmradio.co.mz/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_4422a2792ef85de16be8",
    "name": "Rádio 99Fm Moz",
    "country": "MZ",
    "subdivision": "Maputo",
    "languages": [
      "pt"
    ],
    "categories": [
      "news",
      "talk"
    ],
    "tags": [
      "news",
      "talk"
    ],
    "homepage": "https://www.99fm.co.mz/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:45:55Z"
  },
  {
    "id": "awb_a7788e5d8ea08ff42464",
    "name": "Rádio Cidade - Beira 105.2 FM",
    "country": "MZ",
    "subdivision": null,
    "languages": [
      "pt"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://www.rm.co.mz/canais/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T05:53:10Z"
  },
  {
    "id": "awb_085ed69b04d79a3741b4",
    "name": "Rádio Egea Gospel - Heaven Full",
    "country": "MZ",
    "subdivision": "Maputo",
    "languages": [
      "pt"
    ],
    "categories": [
      "religious"
    ],
    "tags": [
      "christian",
      "gospel",
      "religious"
    ],
    "homepage": "https://radio-egea-web-24hrs.mdn.live/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:48:17Z"
  },
  {
    "id": "awb_cc5b7712a62c69c1b0ac",
    "name": "Radio Fot Lichinga",
    "country": "MZ",
    "subdivision": "Lichinga",
    "languages": [
      "pt"
    ],
    "categories": [
      "news",
      "religious",
      "talk"
    ],
    "tags": [
      "news",
      "religious",
      "talk"
    ],
    "homepage": "https://fotradiolichinga.blogspot.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:46:23Z"
  },
  {
    "id": "awb_c0a64ca15a9714da1633",
    "name": "Radio Maria Moçambique",
    "country": "MZ",
    "subdivision": "Maputo",
    "languages": [
      "pt"
    ],
    "categories": [
      "religious",
      "talk"
    ],
    "tags": [
      "christian",
      "gospel",
      "religious",
      "talk"
    ],
    "homepage": "https://www.radiomaria.org.mz/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:45:55Z"
  },
  {
    "id": "awb_b3d11c5c026fe1a0c9e5",
    "name": "Rádio Miramar",
    "country": "MZ",
    "subdivision": "Maputo",
    "languages": [
      "pt"
    ],
    "categories": [
      "news",
      "pop",
      "talk"
    ],
    "tags": [
      "news",
      "pop",
      "talk"
    ],
    "homepage": "https://miramar.co.mz/radio",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:46:23Z"
  },
  {
    "id": "awb_33cc8c4abd130e5946aa",
    "name": "Rádio Moçambique Antena Nacional",
    "country": "MZ",
    "subdivision": null,
    "languages": [
      "pt"
    ],
    "categories": [
      "news"
    ],
    "tags": [
      "news"
    ],
    "homepage": "https://www.rm.co.mz/rm.co.mz/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T07:20:36Z"
  },
  {
    "id": "awb_72169ff5b8d1a0c3e8b4",
    "name": "Rádio Moçambique Emissor Provincial de Nampula",
    "country": "MZ",
    "subdivision": "Nampula",
    "languages": [
      "pt"
    ],
    "categories": [
      "folk",
      "news",
      "talk"
    ],
    "tags": [
      "folk",
      "news",
      "talk"
    ],
    "homepage": "https://www.rm.co.mz/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:45:55Z"
  },
  {
    "id": "awb_4804af30e09ced221796",
    "name": "Radio Sofala FM",
    "country": "MZ",
    "subdivision": "Beira",
    "languages": [
      "pt"
    ],
    "categories": [
      "pop",
      "talk"
    ],
    "tags": [
      "pop",
      "talk",
      "top 40"
    ],
    "homepage": "https://play.google.com/store/apps/details?id=com.radiosofala.fm",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:46:23Z"
  },
  {
    "id": "awb_97fd9b9f2b0b1d8c4ed9",
    "name": "Rádio Terra",
    "country": "MZ",
    "subdivision": "Maputo",
    "languages": [
      "pt"
    ],
    "categories": [
      "news",
      "talk"
    ],
    "tags": [
      "news",
      "talk"
    ],
    "homepage": "https://radioterra.online/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-10-16T09:46:23Z"
  },
  {
    "id": "awb_0cce6e6a27ff54ec4d27",
    "name": "Super FM 101.9",
    "country": "MZ",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://superfm.folhademaputo.co.mz/",
    "favicon": "https://static.folhademaputo.co.mz/images_sfm/logo_superfm_108.png",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:07Z"
  }
]

=== AirwaveDB/database/data/stations/TC.json
[
  {
    "id": "awb_bbf1301c55fc7114ae39",
    "name": "Abdulbasit Abdulsamad",
    "country": "TC",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T04:43:25Z"
  }
]

=== AirwaveDB/database/data/stations/SM.json
[
  {
    "id": "awb_a0e312d2739d7c69a10d",
    "name": "Abdulbasit Abdulsamad",
    "country": "SM",
    "subdivision": null,
    "languages": [
      "ar"
    ],
    "categories": [],
    "tags": [],
    "homepage": "https://mp3islam.com/",
    "favicon": null,
    "type": null,
    "sourceCount": 2,
    "updatedAt": "2026-08-23"
  },
  {
    "id": "awb_18b2854c6754acd5b7b5",
    "name": "Public Radio of San Marino",
    "country": "SM",
    "subdivision": null,
    "languages": [],
    "categories": [],
    "tags": [],
    "homepage": "https://www.sanmarinortv.sm/radio",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-02-28T17:11:19Z"
  },
  {
    "id": "awb_48b94dd8a2c294520c8c",
    "name": "Radio San Marino",
    "country": "SM",
    "subdivision": "Città di San Marino",
    "languages": [
      "it"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "città di san marino",
      "pop",
      "top 40"
    ],
    "homepage": "https://www.smtvsanmarino.sm/radio/ascolta-radio-san-marino",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T04:51:20Z"
  },
  {
    "id": "awb_8cb7c00789b9880bd58d",
    "name": "Radio San Marino",
    "country": "SM",
    "subdivision": null,
    "languages": [],
    "categories": [
      "pop"
    ],
    "tags": [
      "pop"
    ],
    "homepage": null,
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-14T22:54:03Z"
  },
  {
    "id": "awb_1350d96faa7159007829",
    "name": "Radio San Marino Classic",
    "country": "SM",
    "subdivision": null,
    "languages": [
      "it"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "adult contemporary",
      "pop",
      "top 40"
    ],
    "homepage": "https://www.sanmarinortv.sm/radio",
    "favicon": "https://www.sanmarinortv.sm/assets/frontend/img/logo-310-150.png?v54",
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T04:07:09Z"
  },
  {
    "id": "awb_f79f81e42c0e8df1807d",
    "name": "Radio San Marino Classic",
    "country": "SM",
    "subdivision": "Città di San Marino",
    "languages": [
      "it"
    ],
    "categories": [
      "pop"
    ],
    "tags": [
      "città di san marino",
      "classic hits"
    ],
    "homepage": "https://www.smtvsanmarino.sm/radio/ascolta-radio-classic",
    "favicon": null,
    "type": null,
    "sourceCount": 1,
    "updatedAt": "2026-01-15T04:47:54Z"
  },
  {
    "id": "awb_8033c75b34c628cd7cb6",
    "name": "USMARADIO",
    "country": "SM",
    "subdivision": "Città di San Marino",
    "languages": [
      "it"
    ],
    "categories": [
      "college"
    ],
    "tags": [
      "città di san marino",
      "university radio"
    ],
    "homepage": "http://www.usmaradio.org/",
    "favicon": "http://www.usmaradio.org/wp-content/uploads/2016/09/usma_logo_new_alpha_h100.png",
    "type": "college",
    "sourceCount": 1,
    "updatedAt": "2026-01-15T00:05:50Z"
  }
]
